language: ruby
install:
  - git clone https://github.com/thinca/vim-themis
  - git clone https://github.com/vim-jp/vital.vim
  - git clone https://github.com/lambdalisue/vital-System-Cache-Simple
script:
  - vim --version
  - vim-themis/bin/themis --reporter spec --runtimepath vital.vim --runtimepath vital-System-Cache-Simple
